apiVersion: v1
kind: Service
metadata:
  name: b6a-sc-springboot-hello
  labels:
    app: b6a-sc-springboot-hello
spec:
  type: NodePort
  ports:
  - port: 9090
  selector:
    app: b6a-sc-springboot-hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b6a-sc-springboot-hello-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: b6a-sc-springboot-hello
        version: v1
    spec:
      containers:
      - name: springboot-helloworld
        image: kasunindrasiri/ballerina_sidecar_springboot_helloworld
        imagePullPolicy: Always #Always
        ports:
        - containerPort: 8080
      - name: ballerinasidecar
        image: kasunindrasiri/ballerinasidecar
        imagePullPolicy: Always #Always
        ports:
        - containerPort: 9090
---
