apiVersion: v1
kind: Service
metadata:
  name: ordermgt
  labels:
    app: ordermgt
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
    name: http
  selector:
    app: ordermgt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordermgt-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordermgt
        version: v1
    spec:
      containers:
      - name: orderwspy
        image: kasunindrasiri/orderwspy
        imagePullPolicy: Always #Always
        ports:
        - containerPort: 5000
      - name: ballerinasidecar
        image: kasunindrasiri/ballerinasidecar
        imagePullPolicy: Always #Always
        ports:
        - containerPort: 9090
---
